# ----
# Site

title: Access To The Cloud
url: "https://accesstothecloud.com"
baseurl: # Not needed because we're not hosting the site in a subfolder

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/logo_with_no_text.svg
description: Product marketing template for Jekyll.
author:
  name: My Name
  email: mail@tombarone.net
  url: https://tombarone.net
  #twitter: # twitter username without the @ symbol
#social:
#  name: Hydra Template
#  links:
#    - https://github.com/CloudCannon/hydra-jekyll-template

# -----
# Build

timezone: Australia/Adelaide

collections:
  staff_members:
    _hide_content: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - Makefile
  - azure_function_apps
