# ----
# Site

title: Access To The Cloud
url: "https://accesstothecloud.com"
baseurl: # Not needed because we're not hosting the site in a subfolder

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/logo_with_no_text.svg
description: Product marketing template for Jekyll.
author:
  name: My Name
  email: mail@tombarone.net
  url: https://tombarone.net

collections:
  staff_members:
    people: true

defaults:
  - scope:
      path: "/assets/icons"
    values:
      output: true
      # Stick all the icon files and things into the root folder on build
      permalink: /

email_endpoint: "https://attc-website-email-trigger.azurewebsites.net"

timezone: Australia/Adelaide

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - Makefile
  - azure_function_apps
